### PR TITLE
move generate categories button out

### PR DESCRIPTION
**Pull request by tiffanyqi**
Button is directly below the categories pie chart and above the table, pulled right. Located on both cumulative and period stats.

### CODE REVIEW

**Comment by tiffanyqi** [comment]
Question: will only those who are admins be able to  use this? It makes a request to "/admin/generate-categories"

**Comment by MaxFangX** [comment]
@tiffanyqi I am not sure, you can check urls.py

**Review by MaxFangX — APPROVED** [review]

**Comment by MaxFangX** [comment]
Verify it works on non-admin and then you can merge!

**Comment by tiffanyqi** [comment]
It works after a user syncs their calendar! Still ready to merge?

**Review by jamesuejio — APPROVED** [review]
This works even if you're not staff! Go ahead and merge Tiffany!

**Pull request merged**
