### PR TITLE
Add toggle zero hour button

### PR DESCRIPTION
**Pull request by jamesuejio**

### CODE REVIEW

**Review by cindytung — APPROVED** [review]
u god

**Review by tiffanyqi — COMMENTED** [review]
.

**Review by tiffanyqi — CHANGES_REQUESTED** [review]
Can you move the button above the table instead of in the table? Thanks :)

**Comment by jamesuejio** [comment]
@tiffanyqi should I just have the button outside like under sync calendars? Like toggle all zero or something? It doesn't make sense to have it separate between tags and categories?

**Comment by tiffanyqi** [comment]
@jalagar ah that's true! I suggest moving it up to the topbar, next to "logout"

**Comment by MaxFangX** [comment]
I don't see the button on the tag list. Am I trippin

**Comment by jamesuejio** [comment]
@MaxFangX I think something is wrong with your javascript, it works for all of us.

**Review by MaxFangX — APPROVED** [review]
wfm

**Pull request closed without merging**
