### PR TITLE
Modify Logged Out and Reset Credentials

### PR DESCRIPTION
**Pull request by tiffanyqi**
- change home page
- change logged in reset credentials
- add pictures
- edit readme for better positioning

### CODE REVIEW

**Comment by tiffanyqi** [comment]
#74

**Review by jamesuejio — APPROVED** [review]
Looks great for v1. Don't forget to merge in master again, we had a bunch of stuff merged in.

**Review by jamesuejio — CHANGES_REQUESTED** [review]
Actually wait the logged in button doesn't work for me. It could be a bower thing, so after you merge master lmk. 

- Also what does change logged in reset credentials mean?

**Comment by MaxFangX** [comment]
Leaving the review of this PR to James or Cindy

**Comment by tiffanyqi** [comment]
@jalagar finally got around to fixing this! The "Sign in" button should now work.

"Reset Credentials" is basically the page in which you click on "connect calendars", I just made that page prettier

**Review by jamesuejio — APPROVED** [review]

**Pull request merged**
