### PR TITLE
Exit out of preloader when user deletes a category

### PR DESCRIPTION
**Pull request by tiffanyqi**
Note: Cindy still can't see the category pie chart with previous preloader code, should this PR also try to fix it?

### CODE REVIEW

**Review by jamesuejio — APPROVED** [review]

**Comment by jamesuejio** [comment]
Works for me. It might just take some time for Cindy I guess..

**Comment by tiffanyqi** [comment]
Yay!

Note: works after you clear cookies, image cache, and possibly restart Chrome

**Review by MaxFangX — APPROVED** [review]
lgtm

**Comment by MaxFangX** [comment]
+2 for slack notif

**Comment by tiffanyqi** [comment]
Closing. Going to merge more-preloader with this one, it's weird that it's making me push max's and cindy's code too

**Pull request closed without merging**
